const masa = new Date()
const hari = masa.getDay()
const minit = masa.getMinutes()
const seconds = masa.getSeconds()
const jam = masa.getHours()
const bulan = masa.getMonth()
console.log(masa)
console.log(`${hari} hari`)
console.log(minit, "mins")
console.log(seconds, "saat")
console.log(jam, "jam")
console.log(bulan + 1, "bulan")